project:
  type: book
  output-dir: docs

sidebar:
  style: docked
  background: light
  logo: figures/NUC.png
  # Add other sidebar options here


book:
  title: "From questions to data to answers using R"
  subtitle: "A guide for students at Newquay University Centre"
  author: "Michael Hunt"
  # date: "7/23/2025"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) Michael Hunt
  repo-url: https://github.com/mbh038/r4nqy
  repo-actions: [edit]
  #downloads: [pdf]
  page-navigation: true
  # cover-image: NUC.png
  chapters:
    - index.qmd
    - part: "Preliminaries"
      chapters: 
      - test_finder.qmd
    - part: "Working with R"
      chapters:
      - install_packages.qmd
      - workflow.qmd
      - ggplot_examples.qmd
      - titles_labels_and_annotations.qmd
    - part: "Tests for difference"
      chapters:
      - tests_for_difference_two_levels.qmd
      - ANOVA_how_it_works_penguins.qmd
      - ANOVA_one_way.qmd
      - ANOVA_two_way_with_model_simplification.qmd
    - part: "Count data"
      chapters:
      - chi-square.qmd
      - fishers-exact-test.qmd
    - part: "Trend data"
      chapters:
      - correlation.qmd
      - simple-linear-regression.qmd
    - part: "Generalised Linear Models (GLM)"
      chapters: 
      - GLM.qmd
      - glm_poisson_with_count_data.qmd
      - glm_with_count_data_ancova.qmd
    - part: "Multivariate Analysis"
      chapters:
      - community_ecology.qmd
      - ordination.qmd
      - PCA.qmd
      - NMDS.qmd
    - part: "Additional help"
      chapters:
      - qq_plots.qmd
      - power-analysis.qmd
    - part: "References"
      chapters:
      - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  warning: false
  message: false

