project:
  type: book
  output-dir: docs

book:
  title: "r4nqy"
  author: "Michael Hunt"
  date: "7/23/2025"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) Michael Hunt
  chapters:
    - index.qmd
    - intro.qmd
    - workflow.qmd
    - t-test-2-sample.qmd
    - test_for_difference_non_parametric.qmd
    - ANOVA_how_it_works.qmd
    - ANOVA_one_way.qmd
    - ANOVA_two_way_with_model_simplification.qmd
    - chi-square.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  warning: false
  message: false

