project:
  type: book
  output-dir: docs

book:
  title: "r4nqy"
  author: "Michael Hunt"
  date: "7/23/2025"
  license: "CC BY-SA"
  page-footer: CC-BY-SA-4.0 (2025) Michael Hunt
  page-navigation: true
  chapters:
    - index.qmd
    - part: "Working with R"
      chapters:
      - workflow.qmd
      - ggplot_examples.qmd
      - titles_labels_and_annotations.qmd
    - part: "Tests for difference"
      chapters:
      - tests_for_difference_two_levels.qmd
      - ANOVA_how_it_works.qmd
      - ANOVA_one_way.qmd
      - ANOVA_two_way_with_model_simplification.qmd
    - part: "Count data"
      chapters:
      - chi-square.qmd
    - part: "Trend data"
      chapters:
      - correlation.qmd
      - simple linear regression.qmd
    - part: "References"
      chapters:
      - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

execute: 
  warning: false
  message: false

